### ISSUE TITLE
Syncing issue

### ISSUE THREAD

**Issue by Philip-Har** [MrNavaStar/InvSync#15]
I'm using Velocity as proxy and when i change server threw the proxy my Inventory is not getting synced. It's only getting synced when i leave the server completly.

**Comment by MrNavaStar** [comment]
Man this issue seems to never go away. What version? I haven't been able to reproduce this behaviour on my own velocity proxy.

**Comment by Khikki** [comment]
I confirm the above, exactly the same situation on 1.18 / build v2.1.

**Comment by MrNavaStar** [comment]
New release should fix this. Please let me know if it does/doesn't

**Comment by Khikki** [comment]
Let know when it will be possible to download new build?

**Comment by MrNavaStar** [comment]
It's on GitHub releases. I will push it to modrinth when someone can verify it works

**Comment by Khikki** [comment]
I will only say that nothing has changed, I will try to update Fabric and Velocity, it is possible that something will change, 
I will record a video to demonstrate this issue.

Issue is specifically when switching to server, with joining the server there is no issue.

**Comment by MrNavaStar** [comment]
Darn, tbh my fix was quite janky. The issue lies with the fact that the fabric join event actually gets called sooner than the fabric disconnect event. I tried adding a delay in the join event to compensate for this, and it's worked on my hardware in the past, However it certainly isn't a stable fix. I'm not 100% sure what I can do to fix this right now. If you want to experiment around, you can build it from source and tweak the timing of the delay. It's in the main class. 

I'll try to find a proper solution to this issue, if you have any ideas I'd love to hear them. I might be able to inject a hook somewhere earlier on in the disconnect process, that's probably a good starting point. 

Thanks for your patience, my time is very limited right now with school, but I'll try to fix this soon.

**Comment by Khikki** [comment]
Can't just load items after the player has logged in?

**Comment by MrNavaStar** [comment]
It seems that simple, but the items must first be written to the database. In order to write to the database one of the servers needs to lock it to let the other server know to wait. That way the right version of the players inventory is always synced. However since the join method is faster, it always beats the disconnecting server to locking that database, resulting in either messed up data or not syncing at all.

**Comment by Khikki** [comment]
So, I put a delay of 10, but there is no change.

`TimeUnit.SECONDS.sleep(10); //Maybe we can find a less shit solution in the future;`

**Comment by Khikki** [comment]
what do you think?

**Comment by MrNavaStar** [comment]
Really? I would have thought that would work. If you open the database is there anything inside it?

**Comment by Khikki** [comment]
As I said earlier, when you log in into server, everything is okay.

**Comment by Khikki** [comment]
Will it be helpful if I record a video?

**Comment by MrNavaStar** [comment]
That is so weird. Yeah that might help

**Comment by Khikki** [comment]
The database looks like this.
[Minecraft.zip](https://github.com/MrNavaStar/InvSync/files/7699454/Minecraft.zip)

**Comment by Khikki** [comment]
As in general, I said earlier, work only with a full leave.
https://youtu.be/ApBJkOYvcPI

**Comment by sqdzy** [comment]
MrNavaStar, the mod saves the player's data exactly when leaving the server, and plugins such as Velocity, for example, work without an exit event

**Comment by Khikki** [comment]
As we figured out with @Squidzydev, issues are saving, not loading.

**Comment by sqdzy** [comment]
![image](https://user-images.githubusercontent.com/53304905/145731252-f5179b73-0149-4e95-8f47-9b5c9aa69056.png)
For what purpose do you need a delay before the player enters the server, if the plugin does not have time to save the data before exiting?
Looked at 2 different databases, when leaving the server and when switching from one to another, when leaving it saves data, when switching to one server to another it does not save, maybe there is a problem with the Velocity settings?

**Comment by MrNavaStar** [comment]
The problem is because the switch from server to server is instant when using velocity. The join event actually gets called sooner than the disconnect event, meaning that the wrong server takes control of the database. The delay fixed this in the 1.17 version, but I guess it no longer works. 

Edit: looking at that screen shot I just realized there is a major bug in that code. Will fix it later today, it could be the culprit.

**Comment by MrNavaStar** [comment]
> MrNavaStar, the mod saves the player's data exactly when leaving the server, and plugins such as Velocity, for example, work without an exit event

Fabric and velocity are separate. I can verify that the disconnect event does get called, but it gets called too late.

**Comment by MrNavaStar** [comment]
Honestly the solution to this issue might be a rewrite of the mod as a velocity plug-in. I'm having difficultys finding a solution to this as a pure fabric mod

**Comment by Khikki** [comment]
We will look forward to it, as inventory sync is really needed :)

**Comment by sqdzy** [comment]
[invsync.zip](https://github.com/MrNavaStar/InvSync/files/7704275/invsync.zip)
It works! @MrNavaStar

**Comment by MrNavaStar** [comment]
How did you fix it? can I see your source code?

**Comment by Khikki** [comment]
yeah, he replaced "**join**" > "init". I will ask him to answer you, we just make one server :D 
As I understand it, you made a mistake in the new version, which was not in 1.17.

**Comment by sqdzy** [comment]
[InvSync2.1.2.zip](https://github.com/MrNavaStar/InvSync/files/7706009/InvSync2.1.2.zip)

**Comment by MrNavaStar** [comment]
Oh interesting. I guess that solves it then. I'll make a new release later today. 

I might still consider rewriting the mod specifically for velocity, as that tends to be what most people use it for. (It might be possible to eliminate the database doing it this way as well) But don't expect that for some time.
