### ISSUE TITLE
Player information cannot be synchronized in real time

### ISSUE THREAD

**Issue by WangJiangJiaoZi** [MrNavaStar/invSync#4]
The server log shows that the database is saved when the player leaves the world.  However, when using Velocity in a game, the information is not guaranteed to be synchronized.

minecraft: 1.16.5
invSync: invsync-v1.1.1

**Comment by Loewetiger** [comment]
I'm having the same issue, using Velocity as well. I'm using invSync 1.2 on two Minecraft 1.17 servers, and switching between them with the `/server` command doesn't sync the items.

However, disconnecting from one server and then connecting the other one does sync everything fine. This could perhaps be fixed by syncing the items a bit after connecting, since the switch via the `/server` command is likely too fast.

**Comment by MrNavaStar** [comment]
Oh weird. This was a weird issue that used to be present with wal mode enabled on the database. Basically one server is trying to read from the database while the other is trying to write. I’ll look into it.

**Comment by MrNavaStar** [comment]
Good news! I have fixed this! sorry for the wait (very busy week), unfortunately I will not be releasing a new 1.16 version as I really only focus on latest releases. However I have made the fixes on the 1.16 branch so you can build the jar from source if you like.
